### ISSUE TITLE
Installation don't works

### ISSUE THREAD

**Issue by MatteoGauthier** [Rigellute/scoop-bucket#3]
```
Error given:
Le chemin d'accès spécifié est introuvable. 1559d3306d9b8f633ebc71e2de5c1f121a4b4945    HEAD 1559d3306d9b8f633ebc71e2de5c1f121a4b4945   refs/heads/master 9e7f36d83d83b0be2d0480e64d135342d01a3288      refs/pull/1/head 6f4fa04bf9dfb51d2ab4defb15943188aa2386e5       refs/pull/2/head
```

**Comment by Rigellute** [comment]
Ah blast, I don't have a Windows machine with me in lockdown. Afraid I can't debug this at the moment. 

I'm about to release v0.18.0 of spotify-tui. Will comment here again once it is ready so you can try installing again.

**Comment by Rigellute** [comment]
Can you try installing now please? Just updated to v0.18.0

**Comment by littleli** [comment]
This is related to #4 

@MattixNow please update to v0.18.0 which is fixed now

**Comment by Rigellute** [comment]
Thanks @littleli, closing this
