### ISSUE TITLE
spotify-tui@0.18.0: hash check failed

### ISSUE THREAD

**Issue by patevs** [Rigellute/scoop-bucket#4]
Checking hash of spotify-tui-windows.tar.gz ... ERROR Hash check failed!
App:         scoop-bucket/spotify-tui
URL:         https://github.com/Rigellute/spotify-tui/releases/download/v0.18.0/spotify-tui-windows.tar.gz
First bytes: 1F 8B 08 00 00 00 00 00
Expected:    5eb9ee319cdb6b65bb70f2b05652a9c2a3bc746a7d4d322b95e6a95ea7a32eb5
Actual:      5eb9ee319cdb6b65bb70f2b05652a9c2a3bc746a7d4d322b95e6a95ea7a32eb5

**Comment by Rigellute** [comment]
Hmm... this is strange. The expected value equals the actual value?

Unfortunately, I don't have a Windows machine with me in covid lockdown to debug this.

Perhaps @littleli could help?

**Comment by littleli** [comment]
> Unfortunately, I don't have a Windows machine with me in covid lockdown to debug this.

Same here. But I'll try to investigate with the resources I have.

**Comment by Rigellute** [comment]
Thank you @littleli 🙏

**Comment by patevs** [comment]
I have a windows machine so let me know if there is anything I can do to help.

**Comment by Rigellute** [comment]
Any help would be appreciated @patevs!

**Comment by littleli** [comment]
@Rigellute I see the problem, take a look at [manifest line 9](https://github.com/Rigellute/scoop-bucket/blob/21684b97ff3994c881a4cb2037f69e324abdf030/spotify-tui.json#L9) there is creeping `^M` sequence (is it ctrl+ something). That's why it's not visible in terminal.

**Comment by patevs** [comment]
Yes I just noticed that too. @littleli You beat me to it by 3 seconds 🤣.

![Annotation 2020-04-23 042236](https://user-images.githubusercontent.com/19348533/80007296-2c791c80-851a-11ea-84ef-868a52ed610a.png)

**Comment by littleli** [comment]
:) no worries, I closed mine. I would ask @Rigellute to check the `scripts/spotify-tui.sh` if it is the source of the problem. If the replacement is done wrong, there needs to be the proper fix in that script too.

**Comment by Rigellute** [comment]
Thanks for the help my friends, I hope you are all holding up well in lockdown!
